import type { ActionRule, CropStageOption, ReplayFrame, Zone } from "./types";

export const cropStages: CropStageOption[] = [
  {
    id: "seedling",
    label: "Seedling",
    shortLabel: "Seedling",
    description: "0-20 days after sowing",
  },
  {
    id: "tillering",
    label: "Tillering",
    shortLabel: "Tillering",
    description: "Canopy expansion and tiller growth",
  },
  {
    id: "heading",
    label: "Heading / flowering",
    shortLabel: "Heading",
    description: "High sensitivity to wind, rain, and disease",
  },
  {
    id: "grain-filling",
    label: "Grain filling",
    shortLabel: "Filling",
    description: "Yield formation before maturity",
  },
  {
    id: "ripening",
    label: "Ripening / harvest",
    shortLabel: "Harvest",
    description: "Harvest readiness and post-rain quality risk",
  },
];

export const zones: Zone[] = [
  {
    id: "da-nang-hoa-vang",
    name: "Hoa Vang upland-irrigated belt",
    shortName: "Hoa Vang",
    currentAdmin: "Da Nang City",
    legacyAdmin: "Former Hoa Vang district, Da Nang",
    coordinates: { lat: 16.026, lng: 108.12 },
    map: { x: 47, y: 24 },
    cropProfile: {
      riceAreaHa: 3150,
      dominantSeason: "Summer-Autumn rice",
      irrigation: "Reservoir-fed canals and small pumping stations",
      advisoryNote: "Flash runoff can rise quickly after mountain rainfall.",
    },
    exposure: {
      floodplain: "medium",
      coastalWind: "medium",
      drainage: "medium",
      elevationBand: "12-90 m",
    },
    currentSignals: {
      forecastRain72hMm: 145,
      rainfallAnomalyPct: 44,
      soilSaturationPct: 68,
      stormDistanceKm: 180,
      stormWindKmh: 92,
      leadTimeHours: 54,
    },
  },
  {
    id: "da-nang-dien-ban-hoi-an",
    name: "Dien Ban - Hoi An lowland rice belt",
    shortName: "Dien Ban - Hoi An",
    currentAdmin: "Da Nang City",
    legacyAdmin: "Former Quang Nam: Dien Ban, Hoi An",
    coordinates: { lat: 15.891, lng: 108.334 },
    map: { x: 59, y: 39 },
    cropProfile: {
      riceAreaHa: 7200,
      dominantSeason: "Winter-Spring and Summer-Autumn rice",
      irrigation: "Canals linked to the Vu Gia - Thu Bon system",
      advisoryNote: "Low-lying paddies face compound river and coastal flooding.",
    },
    exposure: {
      floodplain: "high",
      coastalWind: "high",
      drainage: "medium",
      elevationBand: "0-8 m",
    },
    currentSignals: {
      forecastRain72hMm: 210,
      rainfallAnomalyPct: 71,
      soilSaturationPct: 82,
      stormDistanceKm: 125,
      stormWindKmh: 108,
      leadTimeHours: 42,
    },
  },
  {
    id: "da-nang-thang-binh-coastal",
    name: "Thang Binh coastal plain",
    shortName: "Thang Binh",
    currentAdmin: "Da Nang City",
    legacyAdmin: "Former Quang Nam: Thang Binh",
    coordinates: { lat: 15.678, lng: 108.378 },
    map: { x: 62, y: 55 },
    cropProfile: {
      riceAreaHa: 9600,
      dominantSeason: "Summer-Autumn rice",
      irrigation: "Mixed canal and rainfall-dependent plots",
      advisoryNote: "Large contiguous paddies make early harvest coordination valuable.",
    },
    exposure: {
      floodplain: "high",
      coastalWind: "high",
      drainage: "high",
      elevationBand: "1-15 m",
    },
    currentSignals: {
      forecastRain72hMm: 235,
      rainfallAnomalyPct: 83,
      soilSaturationPct: 86,
      stormDistanceKm: 110,
      stormWindKmh: 118,
      leadTimeHours: 38,
    },
  },
  {
    id: "da-nang-dai-loc-vu-gia",
    name: "Dai Loc - Vu Gia river corridor",
    shortName: "Dai Loc",
    currentAdmin: "Da Nang City",
    legacyAdmin: "Former Quang Nam: Dai Loc",
    coordinates: { lat: 15.88, lng: 107.98 },
    map: { x: 34, y: 42 },
    cropProfile: {
      riceAreaHa: 8100,
      dominantSeason: "Winter-Spring and Summer-Autumn rice",
      irrigation: "Vu Gia river offtakes and local canals",
      advisoryNote: "River rise and upstream release timing are the main watch items.",
    },
    exposure: {
      floodplain: "high",
      coastalWind: "medium",
      drainage: "high",
      elevationBand: "5-40 m",
    },
    currentSignals: {
      forecastRain72hMm: 260,
      rainfallAnomalyPct: 88,
      soilSaturationPct: 91,
      stormDistanceKm: 145,
      stormWindKmh: 104,
      leadTimeHours: 44,
    },
  },
  {
    id: "hue-lagoon-rice",
    name: "Hue lagoon rice and aquaculture edge",
    shortName: "Hue Lagoon",
    currentAdmin: "Hue City",
    legacyAdmin: "Former Thua Thien Hue lagoon communes",
    coordinates: { lat: 16.49, lng: 107.63 },
    map: { x: 39, y: 12 },
    cropProfile: {
      riceAreaHa: 6900,
      dominantSeason: "Winter-Spring rice",
      irrigation: "Lowland canals and lagoon-edge drainage gates",
      advisoryNote: "Wind setup and drainage gate timing can delay field drawdown.",
    },
    exposure: {
      floodplain: "high",
      coastalWind: "medium",
      drainage: "medium",
      elevationBand: "0-10 m",
    },
    currentSignals: {
      forecastRain72hMm: 175,
      rainfallAnomalyPct: 55,
      soilSaturationPct: 76,
      stormDistanceKm: 235,
      stormWindKmh: 84,
      leadTimeHours: 62,
    },
  },
  {
    id: "hue-phong-dien-buffer",
    name: "Phong Dien inland buffer",
    shortName: "Phong Dien",
    currentAdmin: "Hue City",
    legacyAdmin: "Former Phong Dien district, Thua Thien Hue",
    coordinates: { lat: 16.58, lng: 107.39 },
    map: { x: 28, y: 7 },
    cropProfile: {
      riceAreaHa: 5400,
      dominantSeason: "Summer-Autumn rice",
      irrigation: "River and reservoir-supported canals",
      advisoryNote: "Rainfall intensity matters more than direct coastal wind.",
    },
    exposure: {
      floodplain: "medium",
      coastalWind: "low",
      drainage: "medium",
      elevationBand: "8-55 m",
    },
    currentSignals: {
      forecastRain72hMm: 130,
      rainfallAnomalyPct: 34,
      soilSaturationPct: 61,
      stormDistanceKm: 275,
      stormWindKmh: 76,
      leadTimeHours: 68,
    },
  },
];

export const actionRules: ActionRule[] = [
  {
    id: "flood-seedling-drainage",
    hazard: "heavy-rain-flood",
    minSeverity: "high",
    stages: ["seedling"],
    urgency: "now",
    priority: 96,
    action: "Open drainage paths and keep seedling fields from staying submerged for more than a few hours.",
    actionVi:
      "Khai thông mương thoát nước, tránh để ruộng mạ/ngậm nước sâu quá lâu trong vài giờ liên tiếp.",
    rationale: "Seedlings tolerate short wet periods but fail quickly under prolonged submergence.",
  },
  {
    id: "flood-seedling-fertilizer",
    hazard: "heavy-rain-flood",
    minSeverity: "guarded",
    stages: ["seedling"],
    urgency: "24h",
    priority: 74,
    action: "Delay nitrogen fertilizer or herbicide until runoff risk falls.",
    actionVi: "Tạm hoãn bón đạm hoặc phun thuốc cỏ cho đến khi nguy cơ dòng chảy giảm.",
    rationale: "Heavy runoff can waste inputs and contaminate canals.",
  },
  {
    id: "flood-tillering-canal",
    hazard: "heavy-rain-flood",
    minSeverity: "high",
    stages: ["tillering"],
    urgency: "now",
    priority: 93,
    action: "Lower field water level and clear canal gates before the heaviest rain window.",
    actionVi:
      "Hạ mực nước ruộng và dọn cửa cống/mương trước khung giờ mưa lớn nhất.",
    rationale: "Tillering rice recovers better when roots are not oxygen-stressed.",
  },
  {
    id: "flood-heading-disease",
    hazard: "heavy-rain-flood",
    minSeverity: "guarded",
    stages: ["heading"],
    urgency: "24h",
    priority: 86,
    action: "Prepare post-rain inspection for blast and sheath blight on flowering fields.",
    actionVi:
      "Chuẩn bị kiểm tra đạo ôn và khô vằn sau mưa trên ruộng đang trổ bông.",
    rationale: "Wet canopy during heading raises disease pressure.",
  },
  {
    id: "flood-heading-water",
    hazard: "heavy-rain-flood",
    minSeverity: "high",
    stages: ["heading"],
    urgency: "now",
    priority: 95,
    action: "Keep flowering fields shallow-drained; avoid deep standing water during panicle exposure.",
    actionVi:
      "Giữ ruộng trổ bông thoát nước nông, tránh ngập sâu khi bông lúa đang phơi.",
    rationale: "Heading is highly sensitive to combined flooding and lodging.",
  },
  {
    id: "flood-filling-lodging",
    hazard: "heavy-rain-flood",
    minSeverity: "high",
    stages: ["grain-filling"],
    urgency: "24h",
    priority: 84,
    action: "Mark lodging-prone plots and inspect immediately after peak rainfall.",
    actionVi:
      "Đánh dấu thửa ruộng dễ đổ ngã và kiểm tra ngay sau đợt mưa lớn nhất.",
    rationale: "Grain filling losses grow when lodged plants stay wet.",
  },
  {
    id: "flood-ripening-harvest",
    hazard: "heavy-rain-flood",
    minSeverity: "high",
    stages: ["ripening"],
    urgency: "now",
    priority: 98,
    action: "Prioritize early harvest for fields above roughly 80% maturity before prolonged rain.",
    actionVi:
      "Ưu tiên gặt sớm các ruộng đã chín khoảng trên 80% trước đợt mưa kéo dài.",
    rationale: "Harvest-ready rice loses quality quickly after repeated wetting.",
  },
  {
    id: "flood-ripening-drying",
    hazard: "heavy-rain-flood",
    minSeverity: "guarded",
    stages: ["ripening"],
    urgency: "48h",
    priority: 76,
    action: "Reserve drying space and waterproof storage before harvest traffic peaks.",
    actionVi: "Chuẩn bị sân/sấy và chỗ chứa chống nước trước khi nhu cầu gặt tăng cao.",
    rationale: "Drying bottlenecks often turn field risk into post-harvest loss.",
  },
  {
    id: "typhoon-all-assets",
    hazard: "typhoon",
    minSeverity: "guarded",
    stages: "all",
    urgency: "24h",
    priority: 72,
    action: "Secure pumps, fuel, seed, fertilizer, and tarpaulins away from wind and floodwater.",
    actionVi:
      "Cất giữ máy bơm, nhiên liệu, giống, phân bón và bạt ở nơi tránh gió mạnh và nước ngập.",
    rationale: "Protecting inputs keeps recovery actions possible after the event.",
  },
  {
    id: "typhoon-high-community",
    hazard: "typhoon",
    minSeverity: "high",
    stages: "all",
    urgency: "now",
    priority: 90,
    action: "Coordinate with cooperative leaders on harvest labor, drainage crews, and vulnerable households.",
    actionVi:
      "Phối hợp với hợp tác xã về nhân công gặt, tổ thoát nước và hộ dễ bị ảnh hưởng.",
    rationale: "High wind and rain events require shared labor, not isolated field decisions.",
  },
  {
    id: "typhoon-heading-lodging",
    hazard: "typhoon",
    minSeverity: "high",
    stages: ["heading", "grain-filling"],
    urgency: "24h",
    priority: 88,
    action: "Avoid late nitrogen and keep fields shallow to reduce lodging pressure.",
    actionVi:
      "Không bón đạm muộn và giữ nước nông để giảm nguy cơ đổ ngã khi gió mạnh.",
    rationale: "Soft stems and deep water increase lodging during gusts.",
  },
  {
    id: "typhoon-ripening-fast-harvest",
    hazard: "typhoon",
    minSeverity: "high",
    stages: ["ripening"],
    urgency: "now",
    priority: 99,
    action: "Trigger a run-before-storm harvest plan for the ripest plots first.",
    actionVi: "Kích hoạt kế hoạch gặt chạy bão, ưu tiên thửa ruộng chín nhất trước.",
    rationale: "Near-harvest rice has the clearest action path before landfall.",
  },
  {
    id: "typhoon-severe-stop-field",
    hazard: "typhoon",
    minSeverity: "severe",
    stages: "all",
    urgency: "now",
    priority: 100,
    action: "Stop non-essential field work during the danger window and follow official evacuation guidance.",
    actionVi:
      "Dừng việc đồng áng không thiết yếu trong khung giờ nguy hiểm và theo hướng dẫn sơ tán chính thức.",
    rationale: "Worker safety overrides crop operations under severe wind risk.",
  },
  {
    id: "composite-alert-draft",
    hazard: "composite",
    minSeverity: "high",
    stages: "all",
    urgency: "24h",
    priority: 80,
    action: "Prepare one short alert message for farmers, including risk reason and top three actions.",
    actionVi:
      "Soạn một tin nhắn ngắn cho nông dân, nêu lý do rủi ro và ba việc cần làm trước.",
    rationale: "Clear last-mile messaging is the core AgriShield output.",
  },
  {
    id: "composite-monitor",
    hazard: "composite",
    minSeverity: "guarded",
    stages: "all",
    urgency: "72h",
    priority: 50,
    action: "Recheck the advisory when rainfall totals or storm track updates change.",
    actionVi: "Kiểm tra lại khuyến nghị khi tổng mưa hoặc đường đi bão có cập nhật.",
    rationale: "This v1 uses advisory indicators and should update when public signals move.",
  },
];

export const replayFrames: ReplayFrame[] = [
  {
    id: "t-72",
    label: "T-72",
    timestamp: "2022-09-25 04:00 ICT",
    headline: "Noru intensifies east of the Philippines",
    narrative:
      "The storm is still distant, but central Vietnam advisories begin watching track confidence and wet-season soil conditions.",
    stormPosition: { label: "Philippine Sea", x: 92, y: 34 },
    zoneScores: {
      "da-nang-hoa-vang": 31,
      "da-nang-dien-ban-hoi-an": 38,
      "da-nang-thang-binh-coastal": 41,
      "da-nang-dai-loc-vu-gia": 36,
      "hue-lagoon-rice": 27,
      "hue-phong-dien-buffer": 23,
    },
  },
  {
    id: "t-48",
    label: "T-48",
    timestamp: "2022-09-26 04:00 ICT",
    headline: "Westward track aligns with central Vietnam",
    narrative:
      "Typhoon risk rises for coastal Quang Nam - Da Nang advisory zones; action layer starts preparing drainage and harvest decisions.",
    stormPosition: { label: "South China Sea", x: 82, y: 42 },
    zoneScores: {
      "da-nang-hoa-vang": 50,
      "da-nang-dien-ban-hoi-an": 62,
      "da-nang-thang-binh-coastal": 66,
      "da-nang-dai-loc-vu-gia": 58,
      "hue-lagoon-rice": 43,
      "hue-phong-dien-buffer": 35,
    },
  },
  {
    id: "t-24",
    label: "T-24",
    timestamp: "2022-09-27 04:00 ICT",
    headline: "High-impact wind and rainfall window becomes actionable",
    narrative:
      "The demo would prioritize lowland rice, ripening plots, and cooperative coordination before landfall.",
    stormPosition: { label: "Offshore Da Nang", x: 70, y: 48 },
    zoneScores: {
      "da-nang-hoa-vang": 71,
      "da-nang-dien-ban-hoi-an": 84,
      "da-nang-thang-binh-coastal": 88,
      "da-nang-dai-loc-vu-gia": 80,
      "hue-lagoon-rice": 62,
      "hue-phong-dien-buffer": 53,
    },
  },
  {
    id: "landfall",
    label: "Landfall",
    timestamp: "2022-09-28 03:30 ICT",
    headline: "Noru makes landfall around Da Nang - Quang Nam",
    narrative:
      "Composite scores peak where typhoon wind, heavy rainfall, and lowland flood exposure overlap.",
    stormPosition: { label: "Da Nang - Quang Nam", x: 62, y: 43 },
    zoneScores: {
      "da-nang-hoa-vang": 86,
      "da-nang-dien-ban-hoi-an": 95,
      "da-nang-thang-binh-coastal": 97,
      "da-nang-dai-loc-vu-gia": 91,
      "hue-lagoon-rice": 78,
      "hue-phong-dien-buffer": 66,
    },
  },
  {
    id: "t+24",
    label: "T+24",
    timestamp: "2022-09-29 04:00 ICT",
    headline: "Wind weakens, flood response and crop recovery dominate",
    narrative:
      "The recommended workflow shifts from preparation to damage inspection, drainage, disease watch, and post-harvest drying.",
    stormPosition: { label: "Central Highlands", x: 42, y: 54 },
    zoneScores: {
      "da-nang-hoa-vang": 68,
      "da-nang-dien-ban-hoi-an": 82,
      "da-nang-thang-binh-coastal": 85,
      "da-nang-dai-loc-vu-gia": 88,
      "hue-lagoon-rice": 59,
      "hue-phong-dien-buffer": 48,
    },
  },
];
